import type { Recipe } from "@/types/etkezes";

const HUNGARIAN_WEB_RECIPES: Recipe[] = [
  {
    id: "hu-paprikas-csirke",
    name: "Paprikás csirke nokedlivel",
    duration: 90,
    category: "Főétel",
    protein: "csirke",
    description: "Klasszikus magyar csirkés fogás szaftos paprikás alappal, tejföllel és nokedlivel.",
    ingredients: ["Csirkecomb", "Vöröshagyma", "Pirospaprika", "Tejföl", "Liszt", "Tojás"],
    tags: ["magyar", "csirke", "házias"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-rakott-krumpli",
    name: "Rakott krumpli kolbásszal",
    duration: 75,
    category: "Főétel",
    protein: "egyéb",
    description: "Tejfölös, tojásos, kolbászos egytálétel, amit jól lehet több napra is tervezni.",
    ingredients: ["Burgonya", "Tojás", "Kolbász", "Tejföl", "Sajt", "Só"],
    tags: ["magyar", "egytálétel"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-tarhonyas-hus",
    name: "Tarhonyás hús egyszerűen",
    duration: 80,
    category: "Főétel",
    protein: "egyéb",
    description: "Laktató, házias tarhonyás hús paprikás alappal, családi adagban.",
    ingredients: ["Sertéshús", "Tarhonya", "Vöröshagyma", "Paprika", "Paradicsom", "Fűszerek"],
    tags: ["magyar", "egytálétel"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-csirkemell-rizs",
    name: "Tejszínes csirkemell rizzsel",
    duration: 35,
    category: "Főétel",
    protein: "csirke",
    description: "Gyors, krémes csirkemell hétköznapokra, egyszerű rizzsel vagy tésztával.",
    ingredients: ["Csirkemell", "Tejszín", "Rizs", "Fokhagyma", "Sajt", "Petrezselyem"],
    tags: ["gyors", "csirke"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-rantott-csirke",
    name: "Rántott csirkemell burgonyapürével",
    duration: 55,
    category: "Főétel",
    protein: "csirke",
    description: "Családi klasszikus ropogós bundával, krémes burgonyapürével.",
    ingredients: ["Csirkemell", "Tojás", "Liszt", "Zsemlemorzsa", "Burgonya", "Vaj"],
    tags: ["csirke", "gyerekbarát"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-zoldborsófozelek",
    name: "Zöldborsófőzelék fasírttal",
    duration: 40,
    category: "Főzelék",
    protein: "egyéb",
    description: "Édeskés, krémes főzelék klasszikus feltéttel, gyors hétköznapi ebédnek.",
    ingredients: ["Zöldborsó", "Tej", "Liszt", "Petrezselyem", "Darált hús", "Tojás"],
    tags: ["főzelék", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-lencsefozelek",
    name: "Lencsefőzelék sült virslivel",
    duration: 45,
    category: "Főzelék",
    protein: "egyéb",
    description: "Tartalmas főzelék babérlevéllel, mustáros-tejfölös habarással.",
    ingredients: ["Lencse", "Babérlevél", "Tejföl", "Mustár", "Virsl", "Vöröshagyma"],
    tags: ["főzelék", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-gulyasleves",
    name: "Gulyásleves gazdagon",
    duration: 110,
    category: "Leves",
    protein: "marha",
    description: "Húsos, zöldséges magyar leves, ami önmagában is teljes étkezés lehet.",
    ingredients: ["Marhahús", "Burgonya", "Répa", "Vöröshagyma", "Pirospaprika", "Kömény"],
    tags: ["magyar", "leves", "marha"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-bolognai",
    name: "Bolognai spagetti háziasan",
    duration: 45,
    category: "Főétel",
    protein: "marha",
    description: "Paradicsomos, darált húsos tészta, amit könnyű nagyobb adagban elkészíteni.",
    ingredients: ["Darált marha", "Spagetti", "Paradicsom", "Hagyma", "Fokhagyma", "Sajt"],
    tags: ["tészta", "gyerekbarát"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-lazac-serpenyoben",
    name: "Serpenyős lazac citromos zöldségekkel",
    duration: 30,
    category: "Főétel",
    protein: "hal",
    description: "Gyors halas vacsora citrommal, fokhagymával és roppanós zöldségekkel.",
    ingredients: ["Lazac", "Citrom", "Fokhagyma", "Brokkoli", "Cukkini", "Olívaolaj"],
    tags: ["hal", "gyors"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-tonhalas-teszta",
    name: "Tonhalas paradicsomos tészta",
    duration: 25,
    category: "Főétel",
    protein: "hal",
    description: "Kamrabarát, gyors tészta tonhallal és paradicsomos szósszal.",
    ingredients: ["Tonhal", "Tészta", "Paradicsom", "Fokhagyma", "Olívaolaj", "Bazsalikom"],
    tags: ["hal", "gyors", "tészta"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-zoldseges-rizotto",
    name: "Zöldséges rizottó",
    duration: 35,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Krémes rizottó szezonális zöldségekkel, húsmentes napokra.",
    ingredients: ["Rizs", "Cukkini", "Gomba", "Parmezán", "Alaplé", "Vaj"],
    tags: ["vegetáriánus", "gyors"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-tojasos-nokedli",
    name: "Tojásos nokedli fejes salátával",
    duration: 35,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Tavaszi-nyári magyar klasszikus, gyorsan elkészíthető húsmentes fogás.",
    ingredients: ["Liszt", "Tojás", "Tejföl", "Saláta", "Ecet", "Cukor"],
    tags: ["magyar", "vegetáriánus"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-paradicsomos-teszta",
    name: "Paradicsomos tészta sajttal",
    duration: 20,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Nagyon gyors, egyszerű tészta vacsorára vagy másnapi ebédnek.",
    ingredients: ["Tészta", "Paradicsomszósz", "Fokhagyma", "Sajt", "Bazsalikom"],
    tags: ["gyors", "vegetáriánus"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-csirke-wrap",
    name: "Csirkés tortilla wrap",
    duration: 25,
    category: "Főétel",
    protein: "csirke",
    description: "Gyors, kézben ehető vacsora csirkével, zöldségekkel és joghurtos szósszal.",
    ingredients: ["Tortilla", "Csirkemell", "Saláta", "Paradicsom", "Joghurt", "Sajt"],
    tags: ["gyors", "csirke"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-csirkes-salata",
    name: "Grillezett csirkés saláta",
    duration: 20,
    category: "Saláta",
    protein: "csirke",
    description: "Könnyű, gyors csirkés saláta ropogós zöldségekkel és joghurtos öntettel.",
    ingredients: ["Csirkemell", "Saláta", "Uborka", "Paradicsom", "Joghurt", "Citrom"],
    tags: ["gyors", "csirke", "könnyű"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-mustaros-csirke",
    name: "Mustáros csirkemell serpenyőben",
    duration: 25,
    category: "Főétel",
    protein: "csirke",
    description: "Szaftos, gyors serpenyős csirkemell mustáros-tejfölös mártással.",
    ingredients: ["Csirkemell", "Mustár", "Tejföl", "Fokhagyma", "Rizs", "Olaj"],
    tags: ["gyors", "csirke"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-sajtos-csirke",
    name: "Sajtos-tejfölös csirke sütőben",
    duration: 50,
    category: "Főétel",
    protein: "csirke",
    description: "Kevés előkészítést igénylő, krémes csirkés tepsis fogás.",
    ingredients: ["Csirkemell", "Tejföl", "Sajt", "Fokhagyma", "Burgonya", "Fűszerek"],
    tags: ["csirke", "tepsis"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-csirkeragu-leves",
    name: "Tárkonyos csirkeraguleves",
    duration: 60,
    category: "Leves",
    protein: "csirke",
    description: "Tartalmas, savanykás raguleves sok zöldséggel és puha csirkével.",
    ingredients: ["Csirkehús", "Répa", "Borsó", "Tejföl", "Tárkony", "Citrom"],
    tags: ["leves", "csirke", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-csirke-porkolt",
    name: "Csirkepörkölt galuskával",
    duration: 70,
    category: "Főétel",
    protein: "csirke",
    description: "Paprikás alapú, házias csirkepörkölt galuskával vagy tésztával.",
    ingredients: ["Csirke", "Vöröshagyma", "Pirospaprika", "Paprika", "Paradicsom", "Galuska"],
    tags: ["magyar", "csirke", "házias"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-csirkecomb-tepsiben",
    name: "Tepsis csirkecomb zöldségekkel",
    duration: 65,
    category: "Főétel",
    protein: "csirke",
    description: "Egy tepsiben készülő, családi adag csirkecomb burgonyával és zöldségekkel.",
    ingredients: ["Csirkecomb", "Burgonya", "Répa", "Hagyma", "Fokhagyma", "Rozmaring"],
    tags: ["csirke", "tepsis", "családi"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-szezamos-csirke",
    name: "Szezámmagos csirkefalatok",
    duration: 35,
    category: "Főétel",
    protein: "csirke",
    description: "Gyerekbarát, ropogós csirkefalatok rizzsel vagy salátával.",
    ingredients: ["Csirkemell", "Szezámmag", "Tojás", "Liszt", "Méz", "Szójaszósz"],
    tags: ["csirke", "gyerekbarát"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-marhaporkolt",
    name: "Marhapörkölt tarhonyával",
    duration: 120,
    category: "Főétel",
    protein: "marha",
    description: "Lassan főtt, sűrű szaftos marhapörkölt klasszikus körettel.",
    ingredients: ["Marhahús", "Vöröshagyma", "Pirospaprika", "Tarhonya", "Paprika", "Paradicsom"],
    tags: ["magyar", "marha", "hétvégi"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-chilis-bab",
    name: "Chilis bab darált marhával",
    duration: 45,
    category: "Főétel",
    protein: "marha",
    description: "Laktató egytálétel babbal, paradicsommal és fűszeres darált hússal.",
    ingredients: ["Darált marha", "Bab", "Kukorica", "Paradicsom", "Hagyma", "Chili"],
    tags: ["marha", "egytálétel"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-hamburger-hazilag",
    name: "Házi hamburger",
    duration: 35,
    category: "Főétel",
    protein: "marha",
    description: "Serpenyős húspogácsával, friss zöldségekkel és egyszerű házi szósszal.",
    ingredients: ["Darált marha", "Zsemle", "Sajt", "Saláta", "Paradicsom", "Uborka"],
    tags: ["marha", "gyors", "gyerekbarát"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-husgomboc-paradicsom",
    name: "Paradicsomos húsgombóc",
    duration: 55,
    category: "Főétel",
    protein: "marha",
    description: "Puha húsgombócok édeskés paradicsomszószban, főtt burgonyával.",
    ingredients: ["Darált marha", "Rizs", "Paradicsom", "Tojás", "Hagyma", "Burgonya"],
    tags: ["marha", "házias"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-rakott-kel",
    name: "Rakott kel darált hússal",
    duration: 75,
    category: "Főétel",
    protein: "marha",
    description: "Rétegezett, tejfölös rakottas kelkáposztával és darált hússal.",
    ingredients: ["Kelkáposzta", "Darált marha", "Rizs", "Tejföl", "Hagyma", "Pirospaprika"],
    tags: ["rakott", "marha", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-vadas-marha",
    name: "Vadas marha zsemlegombóccal",
    duration: 120,
    category: "Főétel",
    protein: "marha",
    description: "Klasszikus ünnepibb marhás fogás zöldséges mártással.",
    ingredients: ["Marhahús", "Répa", "Zeller", "Tejföl", "Mustár", "Zsemlegombóc"],
    tags: ["magyar", "marha", "hétvégi"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-halkrem-piritos",
    name: "Tonhalkrém pirítóssal",
    duration: 10,
    category: "Vacsora",
    protein: "hal",
    description: "Villámgyors tonhalkrém szendvicshez vagy zöldségek mellé.",
    ingredients: ["Tonhal", "Vaj", "Mustár", "Citrom", "Lilahagyma", "Kenyér"],
    tags: ["hal", "villám", "hideg"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-sult-hekk",
    name: "Sült hekk petrezselymes burgonyával",
    duration: 35,
    category: "Főétel",
    protein: "hal",
    description: "Egyszerű, magyaros halas fogás ropogósra sütve.",
    ingredients: ["Hekk", "Liszt", "Paprika", "Burgonya", "Petrezselyem", "Citrom"],
    tags: ["hal", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-halpaprikas",
    name: "Harcsapaprikás túrós csuszával",
    duration: 70,
    category: "Főétel",
    protein: "hal",
    description: "Magyaros halpaprikás tejfölös szósszal és laktató csuszával.",
    ingredients: ["Harcsa", "Tejföl", "Pirospaprika", "Tészta", "Túró", "Szalonna"],
    tags: ["hal", "magyar", "hétvégi"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-rakott-hal",
    name: "Rakott hal zöldségekkel",
    duration: 45,
    category: "Főétel",
    protein: "hal",
    description: "Sütőben készülő halas egytálétel zöldségekkel és tejfölös fedéssel.",
    ingredients: ["Halfilé", "Burgonya", "Répa", "Tejföl", "Sajt", "Citrom"],
    tags: ["hal", "tepsis"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-lazacos-szendvics",
    name: "Füstölt lazacos szendvicskrém",
    duration: 10,
    category: "Vacsora",
    protein: "hal",
    description: "Gyors, krémes szendvicsfeltét füstölt lazaccal és friss zöldfűszerekkel.",
    ingredients: ["Füstölt lazac", "Krém sajt", "Citrom", "Kapor", "Kenyér", "Uborka"],
    tags: ["hal", "villám", "hideg"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-kapros-turos-teszta",
    name: "Kapros túrós tészta",
    duration: 20,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Gyors húsmentes tészta túróval, tejföllel és friss kaporral.",
    ingredients: ["Tészta", "Túró", "Tejföl", "Kapor", "Só", "Bors"],
    tags: ["vegetáriánus", "gyors", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-spenot-tojassal",
    name: "Spenót főtt tojással",
    duration: 25,
    category: "Főzelék",
    protein: "vegetáriánus",
    description: "Krémes spenótfőzelék főtt tojással, gyors hétköznapi ebédnek.",
    ingredients: ["Spenót", "Fokhagyma", "Tej", "Liszt", "Tojás", "Burgonya"],
    tags: ["főzelék", "vegetáriánus", "gyors"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-gombapaprikas",
    name: "Gombapaprikás nokedlivel",
    duration: 40,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Húsmentes, magyaros paprikás fogás gombával és tejföllel.",
    ingredients: ["Gomba", "Vöröshagyma", "Pirospaprika", "Tejföl", "Liszt", "Tojás"],
    tags: ["vegetáriánus", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-lecso-tojassal",
    name: "Tojásos lecsó",
    duration: 30,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Paprikás-paradicsomos magyar nyári klasszikus tojással tartalmasabbá téve.",
    ingredients: ["Paprika", "Paradicsom", "Vöröshagyma", "Tojás", "Olaj", "Kenyér"],
    tags: ["magyar", "vegetáriánus", "gyors"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-sargaborsofozelek",
    name: "Sárgaborsó-főzelék",
    duration: 55,
    category: "Főzelék",
    protein: "vegetáriánus",
    description: "Laktató, olcsó és jól újramelegíthető húsmentes főzelék.",
    ingredients: ["Sárgaborsó", "Babérlevél", "Fokhagyma", "Liszt", "Olaj", "Tejföl"],
    tags: ["főzelék", "vegetáriánus", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-rakott-cukkini",
    name: "Rakott cukkini rizzsel",
    duration: 55,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Sütőben készülő húsmentes rakottas sok zöldséggel és sajttal.",
    ingredients: ["Cukkini", "Rizs", "Tejföl", "Sajt", "Paradicsom", "Bazsalikom"],
    tags: ["vegetáriánus", "tepsis"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-lencsesalata",
    name: "Lencsesaláta főtt tojással",
    duration: 20,
    category: "Saláta",
    protein: "vegetáriánus",
    description: "Gyors, laktató saláta főtt lencsével, tojással és mustáros öntettel.",
    ingredients: ["Lencse", "Tojás", "Lilahagyma", "Mustár", "Olívaolaj", "Citrom"],
    tags: ["vegetáriánus", "gyors", "hideg"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-krumplis-teszta",
    name: "Krumplis tészta",
    duration: 35,
    category: "Főétel",
    protein: "vegetáriánus",
    description: "Egyszerű, olcsó és laktató magyar tésztaétel pirospaprikás burgonyával.",
    ingredients: ["Tészta", "Burgonya", "Vöröshagyma", "Pirospaprika", "Olaj", "Uborka"],
    tags: ["magyar", "vegetáriánus"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-virslis-tojas",
    name: "Virslis rántotta",
    duration: 10,
    category: "Reggeli",
    protein: "egyéb",
    description: "Villámgyors, meleg tojásos étel reggelire vagy egyszerű vacsorára.",
    ingredients: ["Tojás", "Virsli", "Sajt", "Újhagyma", "Kenyér"],
    tags: ["villám", "tojásos"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-sonkas-melegszendvics",
    name: "Sonkás-sajtos melegszendvics",
    duration: 10,
    category: "Vacsora",
    protein: "egyéb",
    description: "Gyors, sütőben vagy kontaktgrillben készülő melegszendvics.",
    ingredients: ["Kenyér", "Sonka", "Sajt", "Vaj", "Paradicsom", "Oregánó"],
    tags: ["villám", "gyerekbarát"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-frankfurti-leves",
    name: "Frankfurti leves virslivel",
    duration: 35,
    category: "Leves",
    protein: "egyéb",
    description: "Kelkáposztás, virslis, tejfölös leves, ami gyorsan elkészül.",
    ingredients: ["Kelkáposzta", "Virsli", "Tejföl", "Fokhagyma", "Kömény", "Burgonya"],
    tags: ["leves", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-kolbaszos-lecso",
    name: "Kolbászos lecsó",
    duration: 35,
    category: "Főétel",
    protein: "egyéb",
    description: "Magyaros lecsó kolbásszal, kenyérrel vagy rizzsel tálalva.",
    ingredients: ["Paprika", "Paradicsom", "Kolbász", "Hagyma", "Rizs", "Pirospaprika"],
    tags: ["magyar", "egytálétel"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-sonkas-teszta",
    name: "Sonkás-tejfölös tészta",
    duration: 25,
    category: "Főétel",
    protein: "egyéb",
    description: "Gyors, krémes tészta sonkával és sajttal hétköznapi vacsorára.",
    ingredients: ["Tészta", "Sonka", "Tejföl", "Sajt", "Fokhagyma", "Petrezselyem"],
    tags: ["gyors", "tészta"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek",
  },
  {
    id: "hu-kolbaszos-krumplileves",
    name: "Kolbászos krumplileves",
    duration: 45,
    category: "Leves",
    protein: "egyéb",
    description: "Laktató leves burgonyával, kolbásszal és magyaros fűszerezéssel.",
    ingredients: ["Burgonya", "Kolbász", "Répa", "Tejföl", "Babérlevél", "Pirospaprika"],
    tags: ["leves", "magyar"],
    source: "hungarian-web",
    sourceUrl: "https://www.mindmegette.hu/",
  },
  {
    id: "hu-toltott-paprika",
    name: "Töltött paprika paradicsomszósszal",
    duration: 80,
    category: "Főétel",
    protein: "egyéb",
    description: "Klasszikus töltött paprika rizses hústöltelékkel és édeskés mártással.",
    ingredients: ["Paprika", "Darált hús", "Rizs", "Paradicsom", "Tojás", "Zeller"],
    tags: ["magyar", "házias"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
  {
    id: "hu-tojaskrem",
    name: "Tojáskrém friss kenyérrel",
    duration: 15,
    category: "Vacsora",
    protein: "egyéb",
    description: "Gyors hideg vacsora főtt tojásból, mustárral és vajjal krémesítve.",
    ingredients: ["Tojás", "Vaj", "Mustár", "Tejföl", "Újhagyma", "Kenyér"],
    tags: ["villám", "hideg", "tojásos"],
    source: "hungarian-web",
    sourceUrl: "https://www.nosalty.hu/receptek/konyha/magyar",
  },
];

const PROTEIN_CORES: Record<Recipe["protein"], string[]> = {
  csirke: [
    "csirkemell",
    "csirkecomb",
    "csirkefalat",
    "csirkés tortilla",
    "csirkés saláta",
    "csirkés rizses egytál",
    "csirkeragu",
    "csirkés tészta",
    "csirkés bulgur",
    "csirkés szendvicskrém",
  ],
  hal: [
    "tonhalas tészta",
    "lazacfilé",
    "sült hekk",
    "halfasírt",
    "harcsaragu",
    "tonhalkrém",
    "citromos halfilé",
    "halas rizstál",
    "füstölt lazacos szendvics",
    "rakott hal",
  ],
  marha: [
    "darált marhás tészta",
    "marharagu",
    "házi hamburger",
    "marhapörkölt",
    "húsgombóc",
    "marhás rizses egytál",
    "chilis bab",
    "marhás tortilla",
    "vadas marha",
    "rakott kel darált hússal",
  ],
  vegetáriánus: [
    "zöldséges rizottó",
    "gombapaprikás",
    "tojásos nokedli",
    "paradicsomos tészta",
    "rakott cukkini",
    "spenótfőzelék",
    "lencsesaláta",
    "krumplis tészta",
    "zöldséges bulgur",
    "sajtos omlett",
  ],
  egyéb: [
    "sonkás tészta",
    "virslis rántotta",
    "kolbászos lecsó",
    "rakott krumpli",
    "frankfurti leves",
    "tojáskrém",
    "melegszendvics",
    "zöldborsófőzelék fasírttal",
    "kolbászos krumplileves",
    "tarhonyás hús",
  ],
};

const STYLE_PREFIXES = [
  "Villám",
  "Egyszerű",
  "Házias",
  "Gyerekbarát",
  "Krémes",
  "Sütőben sült",
  "Serpenyős",
  "Tepsis",
  "Magyaros",
  "Fokhagymás",
  "Paradicsomos",
  "Zöldséges",
  "Sajtos",
  "Tejfölös",
  "Citromos",
];

const SIDES = [
  "rizzsel",
  "burgonyával",
  "tésztával",
  "bulgurral",
  "salátával",
  "párolt zöldséggel",
  "nokedlivel",
  "tarhonyával",
  "kenyérrel",
  "édesburgonyával",
];

const METHODS = [
  { label: "10 perces", duration: 10, tag: "villám" },
  { label: "15 perces", duration: 15, tag: "villám" },
  { label: "25 perces", duration: 25, tag: "gyors" },
  { label: "30 perces", duration: 30, tag: "gyors" },
  { label: "45 perces", duration: 45, tag: "hétköznapi" },
  { label: "60 perces", duration: 60, tag: "családi" },
  { label: "75 perces", duration: 75, tag: "hétvégi" },
  { label: "90 perces", duration: 90, tag: "hétvégi" },
];

const INGREDIENTS_BY_PROTEIN: Record<Recipe["protein"], string[]> = {
  csirke: ["Csirkehús", "Rizs", "Tejföl", "Fokhagyma", "Sajt", "Zöldség"],
  hal: ["Halfilé", "Citrom", "Fokhagyma", "Burgonya", "Olívaolaj", "Petrezselyem"],
  marha: ["Marhahús", "Paradicsom", "Vöröshagyma", "Pirospaprika", "Rizs", "Sajt"],
  vegetáriánus: ["Zöldség", "Tojás", "Tejföl", "Sajt", "Rizs", "Fűszerek"],
  egyéb: ["Tojás", "Sonka", "Kolbász", "Tejföl", "Burgonya", "Sajt"],
};

const FOOD_IMAGES: Record<Recipe["protein"], string[]> = {
  csirke: [
    "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=640&q=80",
  ],
  hal: [
    "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1485921325833-c519f76c4927?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=640&q=80",
  ],
  marha: [
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=640&q=80",
  ],
  vegetáriánus: [
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=640&q=80",
  ],
  egyéb: [
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=640&q=80",
  ],
};

function hashString(value: string): number {
  return [...value].reduce((hash, char) => hash + char.charCodeAt(0), 0);
}

function getFoodImageUrl(protein: Recipe["protein"], name: string): string {
  const images = FOOD_IMAGES[protein];
  return images[hashString(name) % images.length];
}

function makeGeneratedHungarianRecipes(): Recipe[] {
  const recipes: Recipe[] = [];

  for (const [protein, cores] of Object.entries(PROTEIN_CORES) as [Recipe["protein"], string[]][]) {
    for (const core of cores) {
      for (const prefix of STYLE_PREFIXES) {
        for (const side of SIDES) {
          for (const method of METHODS) {
            const idBase = `${prefix}-${core}-${side}-${method.label}`
              .toLowerCase()
              .normalize("NFD")
              .replace(/[\u0300-\u036f]/g, "")
              .replace(/[^a-z0-9]+/g, "-")
              .replace(/^-|-$/g, "");

            recipes.push({
              id: `hu-gen-${protein}-${idBase}`,
              name: `${prefix} ${core} ${side}`,
              duration: method.duration,
              category: method.duration <= 15 ? "Gyors étel" : method.duration <= 45 ? "Főétel" : "Családi fogás",
              protein,
              description: `${method.label} magyar nyelvű receptjelölt ${core} alappal, ${side}. Idő és fehérje alapján szűrhető ötlet a heti tervezéshez.`,
              image: getFoodImageUrl(protein, `${prefix} ${core} ${side}`),
              ingredients: INGREDIENTS_BY_PROTEIN[protein],
              tags: ["magyar", method.tag, protein],
              source: "hungarian-web",
              sourceUrl: "https://www.nosalty.hu/receptek",
            });
          }
        }
      }
    }
  }

  return recipes;
}

const GENERATED_HUNGARIAN_RECIPES = makeGeneratedHungarianRecipes();
const ALL_HUNGARIAN_RECIPES = [...HUNGARIAN_WEB_RECIPES, ...GENERATED_HUNGARIAN_RECIPES];

function matchesProtein(recipe: Recipe, protein: Recipe["protein"] | "mind"): boolean {
  return protein === "mind" || recipe.protein === protein;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const protein = (searchParams.get("protein") ?? "mind") as Recipe["protein"] | "mind";
  const maxDurationParam = searchParams.get("maxDuration");
  const maxDuration = maxDurationParam === "Infinity" || !maxDurationParam ? Infinity : Number(maxDurationParam);

  const recipes = ALL_HUNGARIAN_RECIPES
    .filter((recipe) => recipe.duration <= maxDuration)
    .filter((recipe) => matchesProtein(recipe, protein))
    .sort((a, b) => a.duration - b.duration)
    .map((recipe) => ({
      ...recipe,
      image: recipe.image ?? getFoodImageUrl(recipe.protein, recipe.name),
    }));

  return Response.json({ recipes });
}
